#theme: jekyll-theme-slate
theme: minimal-mistakes-jekyll
title: Hosseinali Salemi
description: Optimator
search: true
author:
  name: Hosseinali Salemi
  location: "Somewhere"
#remote_theme: benbalter/retlab
#contact_links:
  #- name: Twitter
    #url: https://twitter.com/HASalemi
    #icon: twitter

