theme: jekyll-theme-slate
title: Hosseinali Salemi
description: Optimator
search: true
#remote_theme: benbalter/retlab
#contact_links:
  #- name: Twitter
    #url: https://twitter.com/HASalemi
    #icon: twitter

